.686p
.model flat, c
 ExitProcess PROTO STDCALL :DWORD
 includelib  kernel32.lib  ; ExitProcess 在 kernel32.lib中实现
 printf          PROTO C :VARARG
 scanf          PROTO C :VARARG
 clock proto
 ;STOREDATA PROTO, SAMPLEADD: DWORD
 includelib  libcmt.lib
 includelib  legacy_stdio_definitions.lib
 ;PUBLIC STOREDATA
 ;STOREDATA PROTO C
 EXTERN LOWPTR:DWORD, MIDPTR:DWORD, HIGHPTR:DWORD, MIDCNT:DWORD, SAMPLEADD: DWORD

 SAMPLES  STRUCT
	SAMID  DB 12 DUP('0')   ;每组数据的流水号
	SDA   DD  2540     ;状态信息a
	SDB   DD  0      ;状态信息b
	SDC   DD   0      ;状态信息c
	SF    DD   0        ;处理结果f
SAMPLES  ENDS
.DATA
;LOWPTR DD 0
;MIDF DD 0
;HIGHF DD 0
;MIDCNT DD 0
;SAMPLEADD DD 0

.CODE
STOREDATA PROC C
	MOV ESI, SAMPLEADD
	MOV EAX, [ESI+12]
	MOV EBX, [ESI+16]
	MOV EDX, [ESI+20]
	IMUL EAX, 5
	ADD EAX, EBX
	SUB EAX, EDX
	ADD EAX, 100
	SAR EAX, 7
	MOV DWORD PTR[ESI+24], EAX
	MOV EDX, 0
	CMP EAX, 100
	JZ L1
	JNS L2
	JMP L3

	L1 :
	MOV EDI, MIDPTR; 存入MIDPTR的值，即MIDF区当前地址
	STORECHARMID :
		MOV AL, [ESI]
		MOV BYTE PTR[EDI], AL
		INC ESI
		INC EDI
		INC EDX
		CMP EDX, 12
		JNZ STORECHARMID
		MOV EAX, [ESI]
		MOV DWORD PTR[EDI], EAX
		ADD ESI, 4
		ADD EDI, 4
		MOV EAX, [ESI]
		MOV DWORD PTR[EDI], EAX
		ADD ESI, 4
		ADD EDI, 4
		MOV EAX, [ESI]
		MOV DWORD PTR[EDI], EAX
		ADD ESI, 4
		ADD EDI, 4
		MOV EAX, [ESI]
		MOV DWORD PTR[EDI], EAX
		ADD ESI, 4
		ADD EDI, 4
		INC MIDCNT
		MOV MIDPTR, EDI
		JMP L4
		L2 :
	MOV EDI, HIGHPTR; 存入MIDPTR的值，即MIDF区当前地址
		STORECHARHIGH :
	MOV AL, [ESI]
		MOV BYTE PTR[EDI], AL
		INC ESI
		INC EDI
		INC EDX
		CMP EDX, 12
		JNZ STORECHARHIGH
		MOV EAX, [ESI]
		MOV DWORD PTR[EDI], EAX
		ADD ESI, 4
		ADD EDI, 4
		MOV EAX, [ESI]
		MOV DWORD PTR[EDI], EAX
		ADD ESI, 4
		ADD EDI, 4
		MOV EAX, [ESI]
		MOV DWORD PTR[EDI], EAX
		ADD ESI, 4
		ADD EDI, 4
		MOV EAX, [ESI]
		MOV DWORD PTR[EDI], EAX
		ADD ESI, 4
		ADD EDI, 4
		MOV HIGHPTR, EDI
		JMP L4
		L3 :
	MOV EDI, LOWPTR; 存入MIDPTR的值，即MIDF区当前地址
		STORECHARLOW :
	MOV AL, [ESI]
		MOV BYTE PTR[EDI], AL
		INC ESI
		INC EDI
		INC EDX
		CMP EDX, 12
		JNZ STORECHARLOW
		MOV EAX, [ESI]
		MOV DWORD PTR[EDI], EAX
		ADD ESI, 4
		ADD EDI, 4
		MOV EAX, [ESI]
		MOV DWORD PTR[EDI], EAX
		ADD ESI, 4
		ADD EDI, 4
		MOV EAX, [ESI]
		MOV DWORD PTR[EDI], EAX
		ADD ESI, 4
		ADD EDI, 4
		MOV EAX, [ESI]
		MOV DWORD PTR[EDI], EAX
		ADD ESI, 4
		ADD EDI, 4
		MOV LOWPTR, EDI
		JMP L4
		L4 :
	RET
STOREDATA ENDP
END